// a map so we can use these DYNAMICALLY using the sleeper abbreviations (the keys here)
export const TEAM_BG: Record<string, string> = {
  ARI: 'bg-team-ari',
  ATL: 'bg-team-atl',
  BAL: 'bg-team-bal',
  BUF: 'bg-team-buf',
  CAR: 'bg-team-car',
  CHI: 'bg-team-chi',
  CIN: 'bg-team-cin',
  CLE: 'bg-team-cle',
  DAL: 'bg-team-dal',
  DEN: 'bg-team-den',
  DET: 'bg-team-det',
  GB: 'bg-team-gb',
  HOU: 'bg-team-hou',
  IND: 'bg-team-ind',
  JAX: 'bg-team-jax',
  KC: 'bg-team-kc',
  LAC: 'bg-team-lac',
  LAR: 'bg-team-lar',
  LV: 'bg-team-lv',
  MIA: 'bg-team-mia',
  MIN: 'bg-team-min',
  NE: 'bg-team-ne',
  NO: 'bg-team-no',
  NYG: 'bg-team-nyg',
  NYJ: 'bg-team-nyj',
  PHI: 'bg-team-phi',
  PIT: 'bg-team-pit',
  SEA: 'bg-team-sea',
  SF: 'bg-team-sf',
  TB: 'bg-team-tb',
  TEN: 'bg-team-ten',
  WAS: 'bg-team-was',
};
