/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RostersRouteImport } from './routes/rosters'
import { Route as IndexRouteImport } from './routes/index'

const RostersRoute = RostersRouteImport.update({
  id: '/rosters',
  path: '/rosters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rosters': typeof RostersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rosters': typeof RostersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rosters': typeof RostersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rosters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rosters'
  id: '__root__' | '/' | '/rosters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RostersRoute: typeof RostersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rosters': {
      id: '/rosters'
      path: '/rosters'
      fullPath: '/rosters'
      preLoaderRoute: typeof RostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RostersRoute: RostersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
